airplanes/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from classifieds import views as classifieds_views
from classifieds import forms as classifieds_forms
from django.conf import settings

urlpatterns = [
    # admin urls
    path('admin/', admin.site.urls),

    # registration urls
    path('accounts/register/', classifieds_views.signup,
         name='registration_register'),
    path('accounts/login/', classifieds_views.views_login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # classifieds urls
    path('',include('classifieds.urls')),
    path('mobile-api/',include('classifieds_mobile.urls')),


    # all auth authentication
    path('accounts/', include('allauth.urls')),

    # reset password urls
    path('reset_password/', PasswordResetView.as_view(template_name='registration/reset_password.html'),
         name='reset_password'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset_complete/',
         PasswordResetCompleteView.as_view(template_name='registration/last_reset.html'),
         name='password_reset_complete')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classifieds/urls.py
from django.urls import path
from classifieds import views as classifieds_views

urlpatterns = [

    # Home page url
    path('', classifieds_views.index, name='index'),

    # Contact us page url
    path('contacts/', classifieds_views.contacts, name='contacts'),

    # Classifieds page url
    path('classifieds/', classifieds_views.ClassifiedListView.as_view(), name='classifieds'),

    # Classified page url
    path('classifieds/<int:pk>/', classifieds_views.ClassifiedDetailView.as_view(), name='classified'),
    path('classifieds/<int:pk>/pay/', classifieds_views.classified_pay, name='classified_pay'),
    path('classifieds/<int:pk>/confirm-payment/', classifieds_views.classified_confirm_payment,
         name='classified_confirm_payment'),
    path('classifieds/<int:pk>/activate/', classifieds_views.classified_activate,
         name='classified_activate'),
    path('classifieds/<int:pk>/deactivate/', classifieds_views.classified_deactivate,
         name='classified_deactivate'),

    # users classifieds url
    path('my-classifieds/', classifieds_views.my_classifieds, name='my_classifieds'),
    path('delete-ad/<int:pk>/', classifieds_views.delete_classified, name='delete-ad'),
    path('post-ad-edit/<int:pk>/', classifieds_views.post_ad, name='post_ad_edit'),

    # Ad posting url
    path('post-ad/', classifieds_views.post_ad, name='post_ad'),


    # others
    path('search/', classifieds_views.search, name='search'),
    path('newsletter-subscribe/', classifieds_views.newsletter, name='newsletter'),
]

classifieds/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from django.contrib.auth.validators import validators
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _

from sorl.thumbnail import ImageField


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """User model."""

    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()


class AircraftMake(models.Model):
    make_name = models.CharField(max_length=255)
    number_of_classifieds = models.IntegerField(default=0, editable=False)

    class Meta:
        ordering = ['-number_of_classifieds']

    def __str__(self):
        return self.make_name

    @staticmethod
    def calculate_number_of_classifieds():
        for make in AircraftMake.objects.all():
            make.number_of_classifieds = Classified.objects.filter(aircraft_make=make).count()
            make.save()


class AircraftType(models.Model):
    type_make = models.ForeignKey('AircraftMake', on_delete=models.CASCADE)
    type_name = models.CharField(max_length=255)

    def __str__(self):
        return self.type_name


class Classified(models.Model):
    PARKED = 1
    IN_STORAGE = 2
    AIRWORTHY = 3

    AIRCRAFT_STATUS_CHOICES = (
        (PARKED, 'Parked'),
        (IN_STORAGE, 'In Storage'),
        (AIRWORTHY, 'Airworthy'),
    )

    ACTIVE = 1
    INACTIVE = 2
    AWAITING_PAYMENT = 3

    CLASSIFIED_STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (INACTIVE, 'Inactive'),
        (AWAITING_PAYMENT, 'Awaiting Payment'),
    )

    COMMERCIAL_AIRCRAFT_CHOICES = (
        (True, 'Yes'),
        (False, 'No'),
    )

    YEAR_CHOICES = []
    for r in range(1960, (datetime.datetime.now().year + 1)):
        YEAR_CHOICES.append((r, r))

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_time = models.DateTimeField(auto_now_add=True, editable=False)
    classified_status = models.IntegerField(choices=CLASSIFIED_STATUS_CHOICES, default=ACTIVE)
    payment_completed = models.BooleanField(default=True)

    price_usd = models.FloatField()
    aircraft_type = models.ForeignKey(AircraftType, on_delete=models.CASCADE)
    aircraft_make = models.ForeignKey(AircraftMake, on_delete=models.CASCADE)
    serial_number = models.CharField(max_length=255, blank=True, null=True,validators=[validators.MaxLengthValidator(200,message='The serial number is too large.')])
    year_of_make = models.IntegerField(choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    aircraft_status = models.IntegerField(choices=AIRCRAFT_STATUS_CHOICES, default=PARKED)
    commercial_aircraft = models.BooleanField(default=False, choices=COMMERCIAL_AIRCRAFT_CHOICES)
    description = models.TextField(blank=True, null=True)
    engine_details = models.TextField(blank=True, null=True)
    interior = models.TextField(blank=True, null=True)
    exterior = models.TextField(blank=True, null=True)
    avionics = models.TextField(blank=True, null=True)
    maintenance_status = models.TextField(blank=True, null=True)
    additional_information = models.TextField(blank=True, null=True)

    phone_number = models.CharField(max_length=20,validators=[validators.MaxLengthValidator(17,message='Not a valid '
                                                                                                       'entry'),
                                                              validators.MinLengthValidator(8,message='Not a valid '
                                                                                                      'entry')])
    seller_email = models.EmailField()
    aircraft_location = models.CharField(max_length=255,validators=[validators.MaxLengthValidator(230,message='Address is too large')])
    company_name = models.CharField(max_length=255, blank=True, null=True,validators=[validators.MaxLengthValidator(200,message='Name is too large')])
    company_logo = models.ImageField(blank=True, null=True, upload_to='company_logos')

    class Meta:
        ordering = ['-date_time']

    def __str__(self):
        return self.get_title()

    @staticmethod
    def get_max_price():
        return 5000000

    def get_title(self):
        commercial_str = ""

        if self.commercial_aircraft:
            commercial_str = "Commercial"

        return "%s %s For Sale %s %s ($ %s)" % (
            commercial_str, self.aircraft_type.type_name, self.aircraft_make.make_name, self.year_of_make,
            self.price_usd)

    def get_images(self):
        return ClassifiedImage.objects.filter(classified=self)

    def get_images_count(self):
        return ClassifiedImage.objects.filter(classified=self).count()

    def get_main_image(self):
        images = ClassifiedImage.objects.filter(classified=self)
        if images.count() == 0:
            return False
        else:
            return images.first().get_photo_url()


class ClassifiedImage(models.Model):
    classified = models.ForeignKey(Classified, on_delete=models.CASCADE,related_name='multiple_imgs')
    image = ImageField(upload_to="classified_images")

    def __str__(self):
        return f'{self.classified.aircraft_make} {self.classified.aircraft_type} image'

    def get_photo_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
    # def __unicode__(self):
    #     return "Image for classified #s" % (str(self.classified.id),)


class Newsletter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

classifieds/forms.py
from django import forms
# from registration.forms import RegistrationForm
from django_registration.forms import RegistrationForm
from . import models


class MyCustomUserForm(RegistrationForm):
    class Meta:
        model = models.User
        fields = ['email', 'password1', 'password2']


class ClassifiedForm(forms.ModelForm):
    class Meta:
        model = models.Classified
        exclude = ['user', 'date_time', 'classified_status', 'payment_completed']

        widgets = {
            "commercial_aircraft": forms.RadioSelect(attrs={"class": "list"}),
            "aircraft_type": forms.Select(attrs={"class": "form-control"}),
            "aircraft_make": forms.Select(attrs={"class": "form-control"}),
            "serial_number": forms.TextInput(attrs={"class": "form-control"}),
            "year_of_make": forms.Select(attrs={"class": "form-control"}),
            "aircraft_status": forms.RadioSelect(attrs={"class": "list"}),
            "description": forms.Textarea(attrs={"class": "form-control", "rows": "6"}),
            "engine_details": forms.Textarea(attrs={"class": "form-control", "rows": "2"}),
            "interior": forms.Textarea(attrs={"class": "form-control", "rows": "2"}),
            "exterior": forms.Textarea(attrs={"class": "form-control", "rows": "2"}),
            "avionics": forms.Textarea(attrs={"class": "form-control", "rows": "2"}),
            "maintenance_status": forms.Textarea(attrs={"class": "form-control", "rows": "2"}),
            "additional_information": forms.Textarea(attrs={"class": "form-control", "rows": "2"}),
        }


class ClassifiedImageForm(forms.ModelForm):
    class Meta:
        model = models.ClassifiedImage
        exclude = ['classified']


# class SearchForm(forms.ModelForm):
#     min_price = forms.DecimalField(required=False, widget=forms.NumberInput(attrs={"class": "form-control", "placeholder": "ex: $10000"}))
#     max_price = forms.DecimalField(required=False, widget=forms.NumberInput(attrs={"class": "form-control", "placeholder": "ex: $50000"}))
#
#     min_year = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={"class": "form-control", "placeholder": "ex: 1980"}))
#     max_year = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={"class": "form-control", "placeholder": "ex: 2018"}))
#
#     class Meta:
#         model = models.Classified
#         fields = ['aircraft_type', 'aircraft_make']
#
#         widgets = {
#             "aircraft_type": forms.CheckboxSelectMultiple(),
#             "aircraft_make": forms.CheckboxSelectMultiple(),
#         }
#
#     def __init__(self, *args, **kwargs):
#         super(SearchForm, self).__init__(*args, **kwargs)
#         self.fields['aircraft_type'].empty_label = None
#         self.fields['aircraft_make'].empty_label = None


# class ContactSellerForm(forms.Form):
#     name = forms.CharField(max_length=255, widget=forms.TextInput(attrs={"class": "form-control"}))
#     email = forms.EmailField(widget=forms.TextInput(attrs={"class": "form-control"}))
#     phone = forms.CharField(max_length=20, widget=forms.TextInput(attrs={"class": "form-control"}))
#     message = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control", "rows": "3"}))
#

class ContactForm(forms.Form):
    name = forms.CharField(max_length=255, widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Your name.."}))
    email = forms.EmailField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Your email.."}))
    subject = forms.CharField(max_length=255, widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Subject.."}))
    message = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control", "rows": "8", "placeholder": "Message.."}))

templates/base.html
{#{% load staticfiles %}#}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--[if IE]>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <![endif]-->
    <meta name="description" content="">
    <meta name="author" content="ScriptsBundle">
    <title>RightAircraft | Classifieds Portal</title>

	<!--Font awesome icons link -->
    <script defer src="https://kit.fontawesome.com/359826513d.js" crossorigin="anonymous"></script>

	<!--Google font api link -->
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">

    <!-- =-=-=-=-=-=-= Favicons Icon =-=-=-=-=-=-= -->
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon"/>
    <!-- =-=-=-=-=-=-= Mobile Specific =-=-=-=-=-=-= -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- =-=-=-=-=-=-= Bootstrap CSS Style =-=-=-=-=-=-= -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- =-=-=-=-=-=-= Template CSS Style =-=-=-=-=-=-= -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- =-=-=-=-=-=-= Font Awesome =-=-=-=-=-=-= -->
{#    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" type="text/css">#}
    <!-- =-=-=-=-=-=-= Flat Icon =-=-=-=-=-=-= -->
{#    <link href="{% static 'css/flaticon.css' %}" rel="stylesheet">#}
    <!-- =-=-=-=-=-=-= Et Line Fonts =-=-=-=-=-=-= -->
{#    <link rel="stylesheet" href="{% static 'css/et-line-fonts.css' %}" type="text/css">#}
    <!-- =-=-=-=-=-=-= Menu Drop Down =-=-=-=-=-=-= -->
{#    <link rel="stylesheet" href="{% static 'css/forest-menu.css' %}" type="text/css">#}
    <!-- =-=-=-=-=-=-= Animation =-=-=-=-=-=-= -->
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" type="text/css">
    <!-- =-=-=-=-=-=-= Select Options =-=-=-=-=-=-= -->
{#    <link href="{% static 'css/select2.min.css' %}" rel="stylesheet"/>#}
    <!-- =-=-=-=-=-=-= noUiSlider =-=-=-=-=-=-= -->
{#    <link href="{% static 'css/nouislider.min.css' %}" rel="stylesheet">#}
    <!-- =-=-=-=-=-=-= Listing Slider =-=-=-=-=-=-= -->
{#    <link href="{% static 'css/slider.css' %}" rel="stylesheet">#}
    <!-- =-=-=-=-=-=-= Owl carousel =-=-=-=-=-=-= -->
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.css' %}">#}
{#    <!-- =-=-=-=-=-=-= Check boxes =-=-=-=-=-=-= -->#}
{#    <link href="{% static 'skins/minimal/minimal.css' %}" rel="stylesheet">#}
{#    <!-- =-=-=-=-=-=-= Responsive Media =-=-=-=-=-=-= -->#}
{#    <link href="{% static 'css/responsive-media.css' %}" rel="stylesheet">#}
{#    <!-- =-=-=-=-=-=-= Template Color =-=-=-=-=-=-= -->#}
{#    <link rel="stylesheet" id="color" href="{% static 'css/colors/blue.css' %}">#}
{#    <!-- =-=-=-=-=-=-= For Style Switcher =-=-=-=-=-=-= -->#}
{#    <link rel="stylesheet" id="theme-color" type="text/css" href="#"/>#}
{#    <!-- JavaScripts -->#}
{#    <script src="{% static 'js/modernizr.js' %}"></script>#}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->



    {% block css %}{% endblock %}
</head>
<body>
<!-- =-=-=-=-=-=-= Preloader =-=-=-=-=-=-= -->
<div id="loader-wrapper">
    <div id="loader"></div>
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>
<!--Preloader end -->


<!-- Home Banner 1 -->

	<!-- background image div -->
	<div class="bg-img text-white adjusted-height">

		{% include 'include/navbar.html' %}
{% block content %}

		<!--wrapper div -->
		<div class="d-flex p-4">

			<!-- inner wrapper div -->
			<div class="align-self-center w-60 text-center new-w-90">

				<h1>Buy and sell aircraft globally</h1>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda aut beatae commodi consectetur cumque deleniti dicta eos harum hic illum itaque, labore minima nisi non nulla praesentium quo ratione reiciendis repellendus repudiandae rerum soluta tempore?</p>
				<form action="{% url 'search' %}" method="GET" class="w-60 new-w-90">
					<input type="text" required name="search" placeholder="Keyword, Make, Model S/N" class="custom-form-control w-100">
					<div class="text-right my-3">

						<button class="custom-btn btn-red">Buy</button>

						<button onclick="prevent(event)" class="custom-btn btn-red">Sell</button>

					</div>
				</form>


			</div>
			<!-- inner div end -->

		</div>
		<!--wrapper div end -->
{% endblock content %}



	</div>
	<!-- background image div end -->
	<!-- Home Banner 1 End -->

    <!-- Main Content Area -->
		<div class="bg-black text-white" style="height:fit-content   ">
			{% block static_content %}
				{% include 'include/content.html' %}
			{% endblock %}
		</div>
	<!--Main content area end -->

<!-- footer -->
{% include 'include/footer.html' %}
<!-- footer end -->

<!-- Back To Top -->
<a href="#0" class="cd-top">Top</a>

<!-- =-=-=-=-=-=-= JQUERY =-=-=-=-=-=-= -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- Bootstrap Core Css  -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Jquery Easing -->
<script src="{% static 'js/easing.js' %}"></script>
<!-- Menu Hover  -->
{#<script src="{% static 'js/forest-megamenu.js' %}"></script>#}
<!-- Jquery Appear Plugin -->
{#<script src="{% static 'js/jquery.appear.min.js' %}"></script>#}
<!-- Numbers Animation   -->
{#<script src="{% static 'js/jquery.countTo.js' %}"></script>#}
<!-- Jquery Smooth Scroll  -->
<script src="{% static 'js/jquery.smoothscroll.js' %}"></script>
<!-- Jquery Select Options  -->
{#<script src="{% static 'js/select2.min.js' %}"></script>#}
<!-- noUiSlider -->
{#<script src="{% static 'js/nouislider.all.min.js' %}"></script>#}
{#<!-- Carousel Slider  -->#}
{#<script src="{% static 'js/carousel.min.js' %}"></script>#}
{#<script src="{% static 'js/slide.js' %}"></script>#}
{#<!-- Image Loaded  -->#}
{#<script src="{% static 'js/imagesloaded.js' %}"></script>#}
{#<script src="{% static 'js/isotope.min.js' %}"></script>#}
<!-- CheckBoxes  -->
{#<script src="{% static 'js/icheck.min.js' %}"></script>#}
{#<!-- Jquery Migration  -->#}
{#<script src="{% static 'js/jquery-migrate.min.js' %}"></script>#}
{#<!-- Sticky Bar  -->#}
{#<script src="{% static 'js/theia-sticky-sidebar.js' %}"></script>#}
{#<!-- Style Switcher -->#}
{#<script src="{% static 'js/color-switcher.js' %}"></script>#}
<!-- Template Core JS -->
<script src="{% static 'js/custom.js' %}"></script>
<script type="text/javascript">



</script>
{% block js %}
<script type="text/javascript">

	const bgClass = document.getElementsByClassName('bg-img')

	bgClass[0].style.height = 130+'vh'

	function prevent(e){
	    e.preventDefault()
		location.replace(`${location.origin}/post-ad/`)
	}



	</script>
{% endblock %}
         </body>
</html>

templates/classified_pay.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="main-content-area clearfix">
        <!-- =-=-=-=-=-=-= Latest Ads =-=-=-=-=-=-= -->
        <section class="section-padding error-page pattern-bgs gray ">
            <!-- Main Container -->
            <div class="container">
                <!-- Row -->
                <div class="row">
                    <!-- Middle Content Area -->
                    {% for message in messages %}
                        <div class="col-xs-12">
                            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                        </div>
                    {% endfor %}

                    <div class="col-md-12 col-xs-12 col-sm-12">
                        <div class="well ad-listing clearfix">
                            <div class="col-md-3 col-sm-5 col-xs-12 grid-style no-padding">
                                <!-- Image Box -->
                                <div class="img-box">
                                    {% if classified.get_main_image %}
                                        <img src="{{ classified.get_main_image.image.url }}" class="img-responsive" alt="">
                                    {% else %}
                                        <img src="{% static 'images/posting/car-4.jpg' %}" class="img-responsive" alt="">
                                    {% endif %}

                                    <div class="total-images"><strong>{{ classified.get_images_count }}</strong> photos</div>
                                    <div class="quick-view"><a href="#ad-preview" data-toggle="modal" class="view-button"><i class="fa fa-search"></i></a></div>
                                </div>
                                <!-- Ad Status --><span class="ad-status"> Featured </span>
                                <!-- User Preview -->
                                <div class="user-preview">
                                    {% if classified.company_logo %}
                                        <a href="#"> <img src="{{ classified.company_logo.url }}" class="avatar avatar-small" alt=""> </a>
                                    {% else %}
                                        <a href="#"> <img src="{% static 'images/users/2.jpg' %}" class="avatar avatar-small" alt=""> </a>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-md-9 col-sm-7 col-xs-12">
                                <!-- Ad Content-->
                                <div class="row">
                                    <div class="content-area">
                                        <div class="col-md-9 col-sm-12 col-xs-12">
                                            <!-- Category Title -->
                                            <div class="category-title"><span><a href="{% url 'classifieds' %}?aircraft_type={{ classified.aircraft_type.id }}">{{ classified.aircraft_type.type_name }}</a></span></div>
                                            <!-- Ad Title -->
                                            <h3><a href="{% url 'classified' classified_id=classified.id %}">{{ classified.get_title }}</a></h3>
                                            <!-- Info Icons -->
                                            <ul class="additional-info pull-right">
                                                <li>
                                                    <a data-toggle="tooltip" title="Send Message" href="{% url 'classified' classified_id=classified.id %}" class="fa fa-envelope"></a>
                                                </li>
                                                <li>
                                                    <a data-toggle="tooltip" title="{{ classified.phone_number }}" href="{% url 'classified' classified_id=classified.id %}" class="fa fa-phone"></a>
                                                </li>
                                            </ul>
                                            <!-- Ad Meta Info -->
                                            <ul class="ad-meta-info">
                                                <li><i class="fa fa-map-marker"></i><a href="#">{{ classified.aircraft_location }}</a></li>
                                                <li><i class="fa fa-clock-o"></i>{{ classified.date_time|date:'Y-m-d H:i' }}</li>
                                                {% if classified.commercial_aircraft %}
                                                    <li>
                                                        <span class="badge" style="background-color: #c67605"> Commercial Aircraft </span>
                                                    </li>
                                                {% endif %}
                                            </ul>
                                            <!-- Ad Description-->
                                            <div class="ad-details">
                                                <p>{{ classified.description }}</p>
                                            </div>
                                        </div>
                                        <div class="col-md-3 col-xs-12 col-sm-12">
                                            <!-- Ad Stats -->
                                            <div class="short-info">
                                                <div class="ad-stats hidden-xs"><span>Make  : </span>{{ classified.aircraft_make.make_name }}</div>
                                                <div class="ad-stats hidden-xs"><span>Year : </span>{{ classified.year_of_make }}</div>
                                            </div>
                                            <!-- Price -->
                                            <div class="price"><span>${{ classified.price_usd }}</span></div>
                                            <div class="">Classified Status: <span class="badge">{{ classified.get_classified_status_display }}</span></div>
                                            <div class="">Payment Completed: <span class="badge">{{ classified.payment_completed }}</span></div>
                                            <!-- Ad View Button -->
                                            <a href="{% url 'classified' classified_id=classified.id %}" target="_blank" class="btn btn-block btn-success"><i class="fa fa-eye" aria-hidden="true"></i> View Ad.</a>
{#                                            <a href="{% url 'classified_edit' classified_id=classified.id %}" class="btn btn-block btn-danger"><i class="fa fa-eye" aria-hidden="true"></i> Edit Ad.</a>#}
                                        </div>
                                    </div>
                                </div>
                                <!-- Ad Content End -->
                            </div>
                        </div>
                        <a class="btn btn-success" href="{% url 'classified_confirm_payment' classified_id=classified.id %}">Confirm payment</a>
                    </div>
                    <!-- Middle Content Area  End -->
                </div>
                <!-- Row End -->
            </div>
            <!-- Main Container End -->
        </section>
        <!-- =-=-=-=-=-=-= Ads Archives End =-=-=-=-=-=-= -->
        <!-- =-=-=-=-=-=-= FOOTER =-=-=-=-=-=-= -->
        <!-- =-=-=-=-=-=-= FOOTER END =-=-=-=-=-=-= -->
    </div>
    <!-- Main Content Area End -->
    <!-- Back To Top -->
    <a href="#0" class="cd-top">Top</a>

{% endblock %}


{% block js %}
{% endblock %}